# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1c2e6d87bf319d0f94050a666cb4c6b75f0c55cc9e995efcc24f012c6c4a117d97b7ac457d9f9779da75b59c547fcf861f5c96b959a400124bc36d2ec8ca000

test:
  secret_key_base: 33bb20ac93ef2de8c05018e5992e4681e590514ed92025b5013e4a7d233f70951c7ca7b22f35132e4ccc47964ad014d1771127588f7e0e4359ad440e463b0782

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
